### ISSUE TITLE
深谈已经好久没有代码更新了？

### ISSUE THREAD

**Issue by lishoujun** [martyr-deepin/deepin-talk#7]
你们是在内网开发完了才提交一个受控版本么？

**Comment by manateelazycat** [comment]
我们所有的代码都会实时提交的：
但是 Deepin Talk 已经暂停开发了。 https://gitcafe.com/Deepin

2014-09-05 22:44 GMT+08:00 lishoujun notifications@github.com:

**Comment by lishoujun** [comment]
现在实在github上还是在gitcafe上？
